//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTLVN.QLTLH.Models.SPEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TongLienHoiEntities : DbContext
    {
        public TongLienHoiEntities()
            : base("name=TongLienHoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetPermissionList_Result> GetPermissionList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPermissionList_Result>("GetPermissionList");
        }
    
        public virtual ObjectResult<GiaoPhamThoiGianPhucVu_Result> GiaoPhamThoiGianPhucVu(string tukhoa, Nullable<int> chucvu, Nullable<int> chucdanh, Nullable<int> coquan, Nullable<int> tunam, Nullable<int> dennam, Nullable<int> cachtinh)
        {
            var tukhoaParameter = tukhoa != null ?
                new ObjectParameter("tukhoa", tukhoa) :
                new ObjectParameter("tukhoa", typeof(string));
    
            var chucvuParameter = chucvu.HasValue ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(int));
    
            var chucdanhParameter = chucdanh.HasValue ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(int));
    
            var coquanParameter = coquan.HasValue ?
                new ObjectParameter("coquan", coquan) :
                new ObjectParameter("coquan", typeof(int));
    
            var tunamParameter = tunam.HasValue ?
                new ObjectParameter("tunam", tunam) :
                new ObjectParameter("tunam", typeof(int));
    
            var dennamParameter = dennam.HasValue ?
                new ObjectParameter("dennam", dennam) :
                new ObjectParameter("dennam", typeof(int));
    
            var cachtinhParameter = cachtinh.HasValue ?
                new ObjectParameter("cachtinh", cachtinh) :
                new ObjectParameter("cachtinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiaoPhamThoiGianPhucVu_Result>("GiaoPhamThoiGianPhucVu", tukhoaParameter, chucvuParameter, chucdanhParameter, coquanParameter, tunamParameter, dennamParameter, cachtinhParameter);
        }
    
        public virtual ObjectResult<TimGiaoPham_Result> TimGiaoPham(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimGiaoPham_Result>("TimGiaoPham", searchParameter);
        }
    
        public virtual ObjectResult<TimKiemGiaoPhamHetHan_Result> TimKiemGiaoPhamHetHan(string hovaten, Nullable<System.DateTime> fromdate, Nullable<int> chucdanh, Nullable<System.DateTime> todate)
        {
            var hovatenParameter = hovaten != null ?
                new ObjectParameter("hovaten", hovaten) :
                new ObjectParameter("hovaten", typeof(string));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var chucdanhParameter = chucdanh.HasValue ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(int));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemGiaoPhamHetHan_Result>("TimKiemGiaoPhamHetHan", hovatenParameter, fromdateParameter, chucdanhParameter, todateParameter);
        }
    
        public virtual ObjectResult<TimKiemGiaoPhamNangCao_Result> TimKiemGiaoPhamNangCao(string hovaten, Nullable<int> kethon, Nullable<int> dantoc, Nullable<int> quequan, Nullable<int> nhiemso, Nullable<int> tunamphucvu, Nullable<int> dennamphucvu, Nullable<int> cachtinh, Nullable<int> chucdanh, Nullable<int> chucvu)
        {
            var hovatenParameter = hovaten != null ?
                new ObjectParameter("hovaten", hovaten) :
                new ObjectParameter("hovaten", typeof(string));
    
            var kethonParameter = kethon.HasValue ?
                new ObjectParameter("kethon", kethon) :
                new ObjectParameter("kethon", typeof(int));
    
            var dantocParameter = dantoc.HasValue ?
                new ObjectParameter("dantoc", dantoc) :
                new ObjectParameter("dantoc", typeof(int));
    
            var quequanParameter = quequan.HasValue ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(int));
    
            var nhiemsoParameter = nhiemso.HasValue ?
                new ObjectParameter("nhiemso", nhiemso) :
                new ObjectParameter("nhiemso", typeof(int));
    
            var tunamphucvuParameter = tunamphucvu.HasValue ?
                new ObjectParameter("tunamphucvu", tunamphucvu) :
                new ObjectParameter("tunamphucvu", typeof(int));
    
            var dennamphucvuParameter = dennamphucvu.HasValue ?
                new ObjectParameter("dennamphucvu", dennamphucvu) :
                new ObjectParameter("dennamphucvu", typeof(int));
    
            var cachtinhParameter = cachtinh.HasValue ?
                new ObjectParameter("cachtinh", cachtinh) :
                new ObjectParameter("cachtinh", typeof(int));
    
            var chucdanhParameter = chucdanh.HasValue ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(int));
    
            var chucvuParameter = chucvu.HasValue ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemGiaoPhamNangCao_Result>("TimKiemGiaoPhamNangCao", hovatenParameter, kethonParameter, dantocParameter, quequanParameter, nhiemsoParameter, tunamphucvuParameter, dennamphucvuParameter, cachtinhParameter, chucdanhParameter, chucvuParameter);
        }
    
        public virtual ObjectResult<TimKiemNangCao_Result> TimKiemNangCao(Nullable<int> tinhthanh, Nullable<int> chucvutu, Nullable<int> chucvuden, Nullable<int> nhiemkytu, Nullable<int> nhiemkyden, Nullable<int> namsinhtu, Nullable<int> namsinhden, Nullable<int> tinhtrang, Nullable<int> chucdanh, Nullable<int> chucvu, Nullable<int> nhiemso, Nullable<int> capnhiemso, Nullable<int> dantoc, Nullable<int> hocvi, string cmnd)
        {
            var tinhthanhParameter = tinhthanh.HasValue ?
                new ObjectParameter("tinhthanh", tinhthanh) :
                new ObjectParameter("tinhthanh", typeof(int));
    
            var chucvutuParameter = chucvutu.HasValue ?
                new ObjectParameter("chucvutu", chucvutu) :
                new ObjectParameter("chucvutu", typeof(int));
    
            var chucvudenParameter = chucvuden.HasValue ?
                new ObjectParameter("chucvuden", chucvuden) :
                new ObjectParameter("chucvuden", typeof(int));
    
            var nhiemkytuParameter = nhiemkytu.HasValue ?
                new ObjectParameter("nhiemkytu", nhiemkytu) :
                new ObjectParameter("nhiemkytu", typeof(int));
    
            var nhiemkydenParameter = nhiemkyden.HasValue ?
                new ObjectParameter("nhiemkyden", nhiemkyden) :
                new ObjectParameter("nhiemkyden", typeof(int));
    
            var namsinhtuParameter = namsinhtu.HasValue ?
                new ObjectParameter("namsinhtu", namsinhtu) :
                new ObjectParameter("namsinhtu", typeof(int));
    
            var namsinhdenParameter = namsinhden.HasValue ?
                new ObjectParameter("namsinhden", namsinhden) :
                new ObjectParameter("namsinhden", typeof(int));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            var chucdanhParameter = chucdanh.HasValue ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(int));
    
            var chucvuParameter = chucvu.HasValue ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(int));
    
            var nhiemsoParameter = nhiemso.HasValue ?
                new ObjectParameter("nhiemso", nhiemso) :
                new ObjectParameter("nhiemso", typeof(int));
    
            var capnhiemsoParameter = capnhiemso.HasValue ?
                new ObjectParameter("capnhiemso", capnhiemso) :
                new ObjectParameter("capnhiemso", typeof(int));
    
            var dantocParameter = dantoc.HasValue ?
                new ObjectParameter("dantoc", dantoc) :
                new ObjectParameter("dantoc", typeof(int));
    
            var hocviParameter = hocvi.HasValue ?
                new ObjectParameter("hocvi", hocvi) :
                new ObjectParameter("hocvi", typeof(int));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemNangCao_Result>("TimKiemNangCao", tinhthanhParameter, chucvutuParameter, chucvudenParameter, nhiemkytuParameter, nhiemkydenParameter, namsinhtuParameter, namsinhdenParameter, tinhtrangParameter, chucdanhParameter, chucvuParameter, nhiemsoParameter, capnhiemsoParameter, dantocParameter, hocviParameter, cmndParameter);
        }
    
        public virtual ObjectResult<TimKiemVoiNhieuThamSo_Result> TimKiemVoiNhieuThamSo(string hovaten, Nullable<int> chucDanh, Nullable<int> chucVu, Nullable<int> capchihoi)
        {
            var hovatenParameter = hovaten != null ?
                new ObjectParameter("hovaten", hovaten) :
                new ObjectParameter("hovaten", typeof(string));
    
            var chucDanhParameter = chucDanh.HasValue ?
                new ObjectParameter("ChucDanh", chucDanh) :
                new ObjectParameter("ChucDanh", typeof(int));
    
            var chucVuParameter = chucVu.HasValue ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(int));
    
            var capchihoiParameter = capchihoi.HasValue ?
                new ObjectParameter("capchihoi", capchihoi) :
                new ObjectParameter("capchihoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemVoiNhieuThamSo_Result>("TimKiemVoiNhieuThamSo", hovatenParameter, chucDanhParameter, chucVuParameter, capchihoiParameter);
        }
    }
}
